# Generated by Django 2.1 on 2018-08-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dx1', models.FloatField(verbose_name='X1')),
                ('dx2', models.FloatField(verbose_name='X2')),
                ('dy', models.IntegerField(verbose_name='Y')),
            ],
        ),
    ]
